name: Deploy lambda
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
        
    - name: Zip and update Lambda function
    run: |
      zip -j "${LAMBDA_FUNCTION_NAME}.zip" "./lambdas/${LAMBDA_FUNCTION_NAME}.py"
      aws lambda update-function-code --function-name="$dev_${LAMBDA_FUNCTION_NAME}" --zip-file="fileb://${LAMBDA_FUNCTION_NAME}.zip"
    
    - name: Delay before updating function code
      run: sleep 15
    
    - name: Update lambda env secrets
      run: |
        aws lambda update-function-configuration --function-name="${ENV}_${LAMBDA_FUNCTION_NAME}" --environment "Variables={
        TRELLO_KEY=${{ secrets.DEV_TRELLO_KEY }},
        TRELLO_TOKEN=${{ secrets.DEV_TRELLO_TOKEN }},
        BEEKEEPING_BOARD_ID=${{ secrets.DEV_BEEKEEPING_BOARD_ID }},
        COLLECTIVE_BOARD_ID=${{ secrets.DEV_COLLECTIVE_BOARD_ID }},
        MEETING_BOARD_ID=${{ secrets.DEV_MEETING_BOARD_ID }},
        TRELLO_BOARD_BEEKEEPING=${{ secrets.DEV_TRELLO_BOARD_BEEKEEPING }},
        TRELLO_BOARD_COLLECTIVE=${{ secrets.DEV_TRELLO_BOARD_COLLECTIVE }},
        TRELLO_BOARD_MEETING=${{ secrets.DEV_TRELLO_BOARD_MEETING }}
        }"